services:
  - type: web
    name: fastapi-tattoo-backend
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: HUGGINGFACE_API_TOKEN
        value: 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
